version: '3.8'
services:
  db:
    image: postgres:13.8
    env_file: .env
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - ./src/database/data:/var/lib/postgresql/data
  app:
    env_file: .env
    build: .
    ports:
      - 3001:${PORT}
    depends_on:
      - db
